pagopa/io-functions-services-messages

Notify/__tests__/handler.test.ts
Notify/function.json
Notify/handler.ts
Notify/index.ts
__integrations__/__tests__/notify.tests.ts
__integrations__/utils/fetch.ts
__integrations__/utils/tasks.ts
__mocks__/env-config.mock.ts
__mocks__/express-types.ts
openapi/index.yaml
openapi/index.yaml.template
utils/config.ts

- Add skeleton for new Notify function
- Add tests for middleware
- Update openapi based on tests
Premium Messages, Reminder Notification functionality
Unit tests

[#ICC-205]  Add notify endpoint skeleton

---

templates/__tests__/__snapshots__/template_markdown.test.ts.snap
templates/__tests__/printer.test.ts
templates/__tests__/template_markdown.test.ts
templates/makdown/constant.ts
templates/makdown/message.ts
templates/makdown/reminderPayment.ts
templates/makdown/reminderPaymentLast.ts
templates/makdown/reminderRead.ts
templates/printer.ts

Implements a template printer to compose the notification title and body for the different notification type. This template will be implemented with the same approach used for EU COVID Certification printer..
add template for the 4 notification type
add a printer to route between template
The current notify enpoint on io-backend do not enforce any kind of control on the notification sent. We need to expose a notify endpoint on the platofrm api in order to allow tier 2 component (eg Reminder) to push a notification. With this new approach, we could safenly expose a notify enpoint without loosing control on what is sent to users.
unit test

[#ICC-205] Add printer for notification template

---

helm/values-prod01.yaml

Fix values-prod01.yaml

---

.devops/deploy-pipelines.yml

fix pipeline

---

helm/values-beta.yaml
helm/values-prod01.yaml

fix appinsights key

---

helm/values-beta.yaml
helm/values-prod01.yaml
utils/healthcheck.ts

- Move cosmosdb to prod
- Add messages Azure Storage check to healthcheck
Enable notifications for reminder

[#ICC-205] fix cosmosdb paths + update heathcheck

---

helm/values-beta.yaml
helm/values-prod01.yaml
utils/healthcheck.ts

Rename keyvault var and add new ones

[#ICC-205]  Rename keyvault vars

---

helm/values-beta.yaml
helm/values-prod01.yaml

Set real message content value

[FIX] fix message-content name

---

Notify/__tests__/handler.test.ts
Notify/handler.ts

-  check requireSecureChannel
- add test
Switch reminder notification to anonymous if service require a secure channel
unit test

[#ICCIT-150] switch push to anonymous if requireSecureChannel

---

templates/__tests__/__snapshots__/template_markdown.test.ts.snap
templates/makdown/message.ts

[[#IOCIT-198] remove service name from notification title](https://github.com/pagopa/io-functions-service-messages/commit/5fc58c3f0b92d598934016e5aec843b2536f1a0b)
Do not show service name when verbose push notification are enabled

[#IOCIT-198] Remove service name from notification title

---

.vscode/settings.json
Dockerfile
__integrations__/package.json
__integrations__/yarn.lock
docker/functions-node-14/Dockerfile
extensions.csproj
host.json
package.json
yarn.lock

[#IOCIT-189] - Migrate to functions Runtime v4

---

helm/values-beta.yaml
helm/values-prod01.yaml

see commit history
Update push notification queue to use new fn-pushnotif (updated to runtime v4)

[IOCIT-177] Update pushnotif storage conection string

---

helm/Chart.lock
helm/Chart.yaml
helm/values-beta.yaml
helm/values-prod01.yaml

Upgrade helm chart to 2.3.1

---

Dockerfile

Add permissions for openapi in Dockerfile

---

helm/Chart.lock
helm/Chart.yaml
helm/values-beta.yaml
helm/values-prod01.yaml

[#IOPLT-169] Upgrade Helm Blueprint

---

helm/values-beta.yaml
helm/values-prod01.yaml

fix beta values

---

helm/values-beta.yaml

[#IOPLT-268] Prepare Beta to traffic routing

---

__integrations__/package.json
__integrations__/yarn.lock
middlewares/__tests__/required_headers_middleware.test.ts
middlewares/required_headers_middleware.ts
package.json
yarn.lock

[#IOCOM-755] Fixed function commons and full path id parsing

---

GetRCConfiguration/__tests__/handler.test.ts
GetRCConfiguration/function.json
GetRCConfiguration/handler.ts
GetRCConfiguration/index.ts
__integrations__/__mocks__/mock.remote_content.ts
__integrations__/__tests__/getRCConfiguration.test.ts
openapi/index.yaml
openapi/index.yaml.template

* [Add endpoint for GetRCConfiguration](https://github.com/pagopa/io-functions-service-messages/commit/f0d6212ffa6fafee86a5a66ab1d25a2b4f65ea82);
* [Add new function GetRCConfiguration](https://github.com/pagopa/io-functions-service-messages/commit/a083b19660c1affe9d04436ebf0a4398e7e555a3);
* [Add integration test for GetRCConfiguration](https://github.com/pagopa/io-functions-service-messages/commit/022c65171f59e0c71f8a1af086d2625996bbec3e).
We want to expose a function to get a remote-content configuration
Unit and integration test

[#IOCOM-1064] Add GetRCConfiguration

---

GetRCConfiguration/handler.ts

We need to return the userId in the configuration

[#IOCOM-1156] Return the correct userId

---

helm/values-beta.yaml
helm/values-prod01.yaml

Added vars
Fixed missing vars before deployment

[#IOCOM-1037] Added env vars for changefeed fix

---

openapi/index_external.yaml

- [new external api specifications](https://github.com/pagopa/io-functions-service-messages/commit/74b992e6c2a8e7c574b1be9ee12dde64f8d473fc)
A new specification file has been created to send to external people without exposing fields that they do not need to send because are managed internally

[#IOCOM-1200] New external api specs

---

CreateRCConfiguration/__tests__/handler.test.ts
CreateRCConfiguration/handler.ts
CreateRCConfiguration/index.ts
GetRCConfiguration/__tests__/handler.test.ts
GetRCConfiguration/handler.ts
GetRCConfiguration/index.ts
ListRCConfiguration/__tests__/handler.test.ts
ListRCConfiguration/handler.ts
ListRCConfiguration/index.ts
UpdateRCConfiguration/__tests__/updateRCConfiguration.test.ts
UpdateRCConfiguration/handler.ts
UpdateRCConfiguration/index.ts
__integrations__/__mocks__/fixtures.ts
__integrations__/__mocks__/mock.remote_content.ts
__integrations__/package.json
__integrations__/yarn.lock
__mocks__/remote-content.ts
package.json
utils/mappers.ts
yarn.lock

Moved all RC Configuration functions to use temporary retro-compatible non versioned model.
We are migrating RC Configuration collection to be non versioned.
unit tests
integration tests

[IOCOM-1363] chore(model): moved to temporary non versioned rc_configuration model

---

openapi/index.yaml
openapi/index_internal.yaml.template

Fixed base url with internal url.
Base url for internal api was wrong.
Build

[IOCOM-1442] fix: fixed base url for internal APIs
